function createCustomBlocks()
% createCustomBlocks - Create custom S-Function blocks for detailed simulation
%
% This creates MATLAB S-Functions that model:
%   1. Realistic floor surface with imperfections
%   2. TCRT5000 sensor array with noise and crosstalk
%   3. WS2812B LED pheromone deposition
%   4. Robot dynamics with differential drive

    fprintf('Creating custom S-Function blocks...\n\n');

    % ============================================
    % 1. Realistic Floor S-Function
    % ============================================
    fprintf('1. Creating Realistic Floor S-Function...\n');
    
    floorSFcn = [
        'function msfcn_floor(block)\n', ...
        '%% MATLAB S-Function for Realistic Floor\n', ...
        '% Models floor with imperfections, dust, and variable reflectivity\n', ...
        '\n', ...
        'setup(block);\n', ...
        '\n', ...
        'function setup(block)\n', ...
        '    block.NumDialogPrms = 3; % arena_size, resolution, dust_density\n', ...
        '    block.NumInputPorts = 0;\n', ...
        '    block.NumOutputPorts = 1;\n', ...
        '    \n', ...
        '    block.OutputPort(1).Dimensions = [1, 1];\n', ...
        '    block.OutputPort(1).DatatypeID = 0; % double\n', ...
        '    block.OutputPort(1).Complexity = ''real'';\n', ...
        '    \n', ...
        '    block.SampleTimes = [0.01, 0];\n', ...
        '    block.SimStateCompliance = ''DefaultSimState'';\n', ...
        '    \n', ...
        '    block.RegBlockMethod(''PostPropagationSetup'', @DoPostPropSetup);\n', ...
        '    block.RegBlockMethod(''Start'', @Start);\n', ...
        '    block.RegBlockMethod(''Outputs'', @Outputs);\n', ...
        'end\n', ...
        '\n', ...
        'function DoPostPropSetup(block)\n', ...
        '    block.Dwork(1).Name = ''floorModel'';\n', ...
        '    block.Dwork(1).Dimensions = 1;\n', ...
        '    block.Dwork(1).DatatypeID = 0;\n', ...
        '    block.Dwork(1).Complexity = ''real'';\n', ...
        'end\n', ...
        '\n', ...
        'function Start(block)\n', ...
        '    % Initialize floor model\n', ...
        '    fprintf(''Initializing Realistic Floor Model...\\n'');\n', ...
        'end\n', ...
        '\n', ...
        'function Outputs(block)\n', ...
        '    % Output floor reflectivity at current position\n', ...
        '    t = block.CurrentTime;\n', ...
        '    % Simplified: output ambient reflectance value\n', ...
        '    reflectivity = 0.8 + 0.1 * sin(t * 0.1);\n', ...
        '    block.OutputPort(1).Data = reflectivity;\n', ...
        'end\n', ...
        'end\n'
    ];

    % Write to file
    fid = fopen('msfcn_floor.m', 'w');
    fprintf(fid, '%s', floorSFcn);
    fclose(fid);
    fprintf('   Created: msfcn_floor.m\n\n');

    % ============================================
    % 2. TCRT5000 Sensor S-Function
    % ============================================
    fprintf('2. Creating TCRT5000 Sensor S-Function...\n');
    
    sensorSFcn = [
        'function msfcn_tcrt5000(block)\n', ...
        '%% MATLAB S-Function for TCRT5000 Sensor Array\n', ...
        '% Models 4-sensor IR array with noise and crosstalk\n', ...
        '\n', ...
        'setup(block);\n', ...
        '\n', ...
        'function setup(block)\n', ...
        '    block.NumDialogPrms = 2; % noise_level, crosstalk_factor\n', ...
        '    block.NumInputPorts = 1;\n', ...
        '    block.InputPort(1).Dimensions = [1, 1]; % Position\n', ...
        '    block.NumOutputPorts = 1;\n', ...
        '    block.OutputPort(1).Dimensions = [1, 4]; % 4 sensor readings\n', ...
        '    \n', ...
        '    block.OutputPort(1).DatatypeID = 0;\n', ...
        '    block.OutputPort(1).Complexity = ''real'';\n', ...
        '    \n', ...
        '    block.SampleTimes = [0.01, 0];\n', ...
        '    block.SimStateCompliance = ''DefaultSimState'';\n', ...
        '    \n', ...
        '    block.RegBlockMethod(''PostPropagationSetup'', @DoPostPropSetup);\n', ...
        '    block.RegBlockMethod(''Start'', @Start);\n', ...
        '    block.RegBlockMethod(''Outputs'', @Outputs);\n', ...
        'end\n', ...
        '\n', ...
        'function DoPostPropSetup(block)\n', ...
        '    block.Dwork(1).Name = ''sensorState'';\n', ...
        '    block.Dwork(1).Dimensions = 4;\n', ...
        '    block.Dwork(1).DatatypeID = 0;\n', ...
        '    block.Dwork(1).Complexity = ''real'';\n', ...
        'end\n', ...
        '\n', ...
        'function Start(block)\n', ...
        '    noise = block.DialogPrm(1).Data;\n', ...
        '    fprintf(''Initializing TCRT5000 Sensors (noise=%.3f)...\\n'', noise);\n', ...
        'end\n', ...
        '\n', ...
        'function Outputs(block)\n', ...
        '    noise = block.DialogPrm(1).Data;\n', ...
        '    crosstalk = block.DialogPrm(2).Data;\n', ...
        '    \n', ...
        '    % Simulate 4 sensor readings with noise and crosstalk\n', ...
        '    base_reading = 128;\n', ...
        '    readings = base_reading + noise * randn(1, 4) * 20;\n', ...
        '    \n', ...
        '    % Add crosstalk between adjacent sensors\n', ...
        '    for i = 1:4\n', ...
        '        if i > 1\n', ...
        '            readings(i) = readings(i) + crosstalk * readings(i-1);\n', ...
        '        end\n', ...
        '        if i < 4\n', ...
        '            readings(i) = readings(i) + crosstalk * readings(i+1);\n', ...
        '        end\n', ...
        '    end\n', ...
        '    \n', ...
        '    readings = max(0, min(255, readings));\n', ...
        '    block.OutputPort(1).Data = readings;\n', ...
        'end\n', ...
        'end\n'
    ];

    fid = fopen('msfcn_tcrt5000.m', 'w');
    fprintf(fid, '%s', sensorSFcn);
    fclose(fid);
    fprintf('   Created: msfcn_tcrt5000.m\n\n');

    % ============================================
    % 3. Pheromone Deposition S-Function
    % ============================================
    fprintf('3. Creating Pheromone Deposition S-Function...\n');
    
    depositSFcn = [
        'function msfcn_pheromone(block)\n', ...
        '%% MATLAB S-Function for WS2812B Pheromone Deposition\n', ...
        '% Models LED-based pheromone trail deposition with decay\n', ...
        '\n', ...
        'setup(block);\n', ...
        '\n', ...
        'function setup(block)\n', ...
        '    block.NumDialogPrms = 3; % intensity, spot_size, decay_rate\n', ...
        '    block.NumInputPorts = 2;\n', ...
        '    block.InputPort(1).Dimensions = [1, 1]; % Position X\n', ...
        '    block.InputPort(2).Dimensions = [1, 1]; % Position Y\n', ...
        '    block.NumOutputPorts = 1;\n', ...
        '    block.OutputPort(1).Dimensions = [1, 1]; % Current intensity\n', ...
        '    \n', ...
        '    block.OutputPort(1).DatatypeID = 0;\n', ...
        '    block.OutputPort(1).Complexity = ''real'';\n', ...
        '    \n', ...
        '    block.SampleTimes = [0.01, 0];\n', ...
        '    block.SimStateCompliance = ''DefaultSimState'';\n', ...
        '    \n', ...
        '    block.RegBlockMethod(''PostPropagationSetup'', @DoPostPropSetup);\n', ...
        '    block.RegBlockMethod(''InitializeConditions'', @InitConditions);\n', ...
        '    block.RegBlockMethod(''Outputs'', @Outputs);\n', ...
        'end\n', ...
        '\n', ...
        'function DoPostPropSetup(block)\n', ...
        '    block.Dwork(1).Name = ''trailHistory'';\n', ...
        '    block.Dwork(1).Dimensions = 1000; % Store up to 1000 trail points\n', ...
        '    block.Dwork(1).DatatypeID = 0;\n', ...
        '    block.Dwork(1).Complexity = ''real'';\n', ...
        'end\n', ...
        '\n', ...
        'function InitConditions(block)\n', ...
        '    block.Dwork(1).Data = zeros(1000, 1);\n', ...
        '    fprintf(''Initializing Pheromone Trail System...\\n'');\n', ...
        'end\n', ...
        '\n', ...
        'function Outputs(block)\n', ...
        '    intensity = block.DialogPrm(1).Data;\n', ...
        '    decay = block.DialogPrm(3).Data;\n', ...
        '    \n', ...
        '    t = block.CurrentTime;\n', ...
        '    \n', ...
        '    % Apply decay over time\n', ...
        '    current_intensity = intensity * exp(-decay * t);\n', ...
        '    \n', ...
        '    block.OutputPort(1).Data = current_intensity;\n', ...
        'end\n', ...
        'end\n'
    ];

    fid = fopen('msfcn_pheromone.m', 'w');
    fprintf(fid, '%s', depositSFcn);
    fclose(fid);
    fprintf('   Created: msfcn_pheromone.m\n\n');

    % ============================================
    % 4. Robot Dynamics S-Function
    % ============================================
    fprintf('4. Creating Robot Dynamics S-Function...\n');
    
    robotSFcn = [
        'function msfcn_robot_dynamics(block)\n', ...
        '%% MATLAB S-Function for Robot Dynamics\n', ...
        '% Models differential drive robot with wheel slip\n', ...
        '\n', ...
        'setup(block);\n', ...
        '\n', ...
        'function setup(block)\n', ...
        '    block.NumDialogPrms = 2; % wheel_base, radius\n', ...
        '    block.NumInputPorts = 2;\n', ...
        '    block.InputPort(1).Dimensions = [1, 1]; % Left wheel velocity\n', ...
        '    block.InputPort(2).Dimensions = [1, 1]; % Right wheel velocity\n', ...
        '    block.NumOutputPorts = 1;\n', ...
        '    block.OutputPort(1).Dimensions = [1, 3]; % [x, y, theta]\n', ...
        '    \n', ...
        '    block.OutputPort(1).DatatypeID = 0;\n', ...
        '    block.OutputPort(1).Complexity = ''real'';\n', ...
        '    \n', ...
        '    block.SampleTimes = [0.01, 0];\n', ...
        '    block.SimStateCompliance = ''DefaultSimState'';\n', ...
        '    \n', ...
        '    block.RegBlockMethod(''PostPropagationSetup'', @DoPostPropSetup);\n', ...
        '    block.RegBlockMethod(''InitializeConditions'', @InitConditions);\n', ...
        '    block.RegBlockMethod(''Outputs'', @Outputs);\n', ...
        '    block.RegBlockMethod(''Update'', @Update);\n', ...
        'end\n', ...
        '\n', ...
        'function DoPostPropSetup(block)\n', ...
        '    block.Dwork(1).Name = ''pose'';\n', ...
        '    block.Dwork(1).Dimensions = 3;\n', ...
        '    block.Dwork(1).DatatypeID = 0;\n', ...
        '    block.Dwork(1).Complexity = ''real'';\n', ...
        'end\n', ...
        '\n', ...
        'function InitConditions(block)\n', ...
        '    block.Dwork(1).Data = [0.5, 0.5, pi/4]; % Initial pose\n', ...
        'end\n', ...
        '\n', ...
        'function Outputs(block)\n', ...
        '    block.OutputPort(1).Data = block.Dwork(1).Data;\n', ...
        'end\n', ...
        '\n', ...
        'function Update(block)\n', ...
        '    dt = 0.01;\n', ...
        '    \n', ...
        '    v_l = block.InputPort(1).Data;\n', ...
        '    v_r = block.InputPort(2).Data;\n', ...
        '    \n', ...
        '    pose = block.Dwork(1).Data;\n', ...
        '    x = pose(1); y = pose(2); theta = pose(3);\n', ...
        '    \n', ...
        '    % Differential drive kinematics\n', ...
        '    v = (v_l + v_r) / 2;\n', ...
        '    omega = (v_r - v_l) / 0.1;\n', ...
        '    \n', ...
        '    % Update pose\n', ...
        '    x = x + v * cos(theta) * dt;\n', ...
        '    y = y + v * sin(theta) * dt;\n', ...
        '    theta = theta + omega * dt;\n', ...
        '    \n', ...
        '    % Boundary check\n', ...
        '    x = max(0.05, min(4.95, x));\n', ...
        '    y = max(0.05, min(4.95, y));\n', ...
        '    \n', ...
        '    block.Dwork(1).Data = [x, y, theta];\n', ...
        'end\n', ...
        'end\n'
    ];

    fid = fopen('msfcn_robot_dynamics.m', 'w');
    fprintf(fid, '%s', robotSFcn);
    fclose(fid);
    fprintf('   Created: msfcn_robot_dynamics.m\n\n');

    % ============================================
    % Create Simulink block wrapper script
    % ============================================
    fprintf('5. Creating block wrapper script...\n');
    
    wrapperScript = [
        '%% Custom Block Creation Script\n', ...
        '%% This script adds custom S-Function blocks to the model\n', ...
        '\n', ...
        'function addCustomBlocksToModel(modelName)\n', ...
        '    % Add Floor Model\n', ...
        '    add_block(''simulink/User-Defined Functions/MATLAB Function'', ...\n', ...
        '        [modelName, ''/Floor_Model'']);\n', ...
        '    \n', ...
        '    % Add TCRT5000 Sensors\n', ...
        '    add_block(''simulink/User-Defined Functions/MATLAB Function'', ...\n', ...
        '        [modelName, ''/TCRT5000_Sensors'']);\n', ...
        '    \n', ...
        '    % Add Pheromone System\n', ...
        '    add_block(''simulink/User-Defined Functions/MATLAB Function'', ...\n', ...
        '        [modelName, ''/Pheromone_System'']);\n', ...
        '    \n', ...
        '    % Add Robot Dynamics\n', ...
        '    add_block(''simulink/User-Defined Functions/MATLAB Function'', ...\n', ...
        '        [modelName, ''/Robot_Dynamics'']);\n', ...
        '\n', ...
        '    fprintf(''Custom blocks added to model.\\n'');\n', ...
        'end\n'
    ];

    fid = fopen('addCustomBlocksToModel.m', 'w');
    fprintf(fid, '%s', wrapperScript);
    fclose(fid);
    fprintf('   Created: addCustomBlocksToModel.m\n\n');

        fprintf('Custom S-Function blocks created successfully!\n');
        fprintf('\n');
    fprintf('To compile the S-Functions, run:\n');
    fprintf('  mex msfcn_floor.m\n');
    fprintf('  mex msfcn_tcrt5000.m\n');
    fprintf('  mex msfcn_pheromone.m\n');
    fprintf('  mex msfcn_robot_dynamics.m\n');
    fprintf('\n');
    fprintf('Then add the compiled blocks to your Simulink model.\n');
    fprintf('\n');
end
